version: "3"
services:
      tfserve:
              image: tensorflow/serving:latest
              restart: unless-stopped
              ports:
                      - 8500:8500
                      - 8501:8501
              volumes:
                      - ${MODEL1_PATH}:/models/${MODEL1_NAME}
                      - ${MODEL2_PATH}:/models/${MODEL2_NAME}
                      - /home/deploy/dcp-file/tf_serving/models.config:/models/models.config
              command: --model_config_file=/models/models.config